AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Resources:
  CreateUserAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./target/api-aws-1.0.0-SNAPSHOT.jar
      FunctionName: GamebookPlatformCreateUserAccount
      Handler: org.sephire.gamebook.awsapi.account.CreateUserAccountFunction
      Description: Creates a user account from the given email and alias
      Runtime: java8
      MemorySize: 128
      Timeout: 10
      Role: "arn:aws:iam::XXX:role/service-role/GamebookPlatformLambdas"

  GetUserAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GamebookPlatformGetUserAccount
      CodeUri: ./target/api-aws-1.0.0-SNAPSHOT.jar
      Handler: org.sephire.gamebook.awsapi.account.GetUserAccountFunction
      Description: Gets the information related to an account
      Runtime: java8
      MemorySize: 128
      Timeout: 10
      Role: "arn:aws:iam::XXX:role/service-role/GamebookPlatformLambdas"
